-- AlterEnum
ALTER TYPE "OrderStatus" ADD VALUE 'EXCHANGE_REQUESTED';
ALTER TYPE "OrderStatus" ADD VALUE 'EXCHANGE_APPROVED';
ALTER TYPE "OrderStatus" ADD VALUE 'EXCHANGE_REJECTED';
ALTER TYPE "OrderStatus" ADD VALUE 'EXCHANGED';
